version: '3'

networks:
    landLoardNet:
        driver: bridge

volumes:
    app_data:
services:
    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: sf4_mysql
        volumes:
            - ./app_data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4
        ports:
            - 3306:3306
        networks:
            - landLoardNet
    sf4_php:
        image: sf4_php:latest
        container_name: sf4_php
        hostname: sf4_php
        volumes:
          - .:/var/www
        environment:
          - maildev_host=sf4_maildev
          - ENV=local
        ports:
          - 8080:80
        depends_on:
          - maildev
          - mysql
        networks:
          - landLoardNet

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf4_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8081:80
        links:
            - mysql
        depends_on:
            - mysql
        networks:
            - landLoardNet
    maildev:
        image: djfarrelly/maildev
        container_name: sf4_maildev
        ports:
            - 8001:80
        networks:
            - landLoardNet